[theme]
# A cor principal dos botões e dos destaques (Ex: um azul marinho ou o vermelho da sua marca)
primaryColor = "#1f77b4"

# A cor do fundo da tela principal (geralmente branco ou um cinza bem claro)
backgroundColor = "#FFFFFF"

# A cor do fundo do menu lateral e dos painéis de métricas
secondaryBackgroundColor = "#F0F2F6"

# A cor dos textos
textColor = "#262730"

# Fonte (Opções: "sans serif", "serif", ou "monospace")
font = "sans serif"